"""This file contains lists of organisms"""

test_orgs = ["Escherichia_coli",
             "Pseudomonas_aeruginosa",
             "Haemophilus_influenzae"]

old_reference_orgs = ['Lactobacillus_johnsonii_NCC_533',
                  'Bacteroides_fragilis_YCH46',
                  'Lactobacillus_acidophilus_NCFM',
                  'Lactobacillus_salivarius_UCC118',
                  'Lactobacillus_gasseri_ATCC_33323',
                  'Lactobacillus_casei_ATCC_334',
                  'Lactobacillus_reuteri_DSM_20016',
                  'Methanobrevibacter_smithii_ATCC_35061',
                  'Bacteroides_caccae_ATCC_43185',
                  'Collinsella_aerofaciens_ATCC_25986',
                  'Lactobacillus_brevis_ATCC_367',
                  'Bifidobacterium_adolescentis_ATCC_15703',
                  'Ruminococcus_torques_ATCC_27756',
                  'Bacteroides_stercoris_ATCC_43183',
                  'Ruminococcus_obeum_ATCC_29174',
                  'Bryantella_formatexigens_DSM_14469',
                  'Providencia_rustigianii_DSM_4541',
                  'Mitsuokella_multacida_DSM_20544',
                  'Clostridium_nexile_DSM_1787',
                  'Clostridium_hiranonis_DSM_13275',
                  'Butyrivibrio_crossotus_DSM_2876',
                  'Prevotella_copri_DSM_18205',
                  'Bacteroides_cellulosilyticus_DSM_14838',
                  'Alistipes_putredinis_DSM_17216',
                  'Enterobacter_cancerogenus_ATCC_35316',
                  'Bacteroides_coprophilus_DSM_18228',
                  'Fusobacterium_7_1',
                  'Collinsella_stercoris_DSM_13279',
                  'Blautia_hansenii_DSM_20583',
                  'Parabacteroides_johnsonii_DSM_18315',
                  'Clostridium_bolteae_ATCC_BAA_613',
                  'Helicobacter_bilis_ATCC_43879',
                  'Bifidobacterium_longum_subsp._longum_ATCC_55813',
                  'Clostridium_sporogenes_ATCC_15579',
                  'Bacteroides_intestinalis_DSM_17393',
                  'Ruminococcus_lactaris_ATCC_29176',
                  'Providencia_stuartii_ATCC_25827',
                  'Eubacterium_dolichum_DSM_3991',
                  'Clostridium_spiroforme_DSM_1552',
                  'Clostridium_leptum_DSM_753',
                  'Enterococcus_faecalis_TX0104',
                  'Eubacterium_siraeum_DSM_15702',
                  'Helicobacter_cinaedi_CCUG_18818',
                  'Lactobacillus_ruminis_ATCC_25644',
                  'Blautia_hydrogenotrophica_DSM_10507',
                  'Gordonibacter_pamelaeae_7_10_1_b',
                  'Lactobacillus_fermentum_ATCC_14931',
                  'Collinsella_intestinalis_DSM_13280',
                  'Anaerofustis_stercorihominis_DSM_17244',
                  'Clostridium_bartlettii_DSM_16795',
                  'Anaerotruncus_colihominis_DSM_17241',
                  'Clostridium_ramosum_DSM_1402',
                  'Proteus_penneri_ATCC_35198',
                  'Anaerococcus_hydrogenalis_DSM_7454',
                  'Bacteroides_coprocola_DSM_17136',
                  'Coprococcus_comes_ATCC_27758',
                  'Eubacterium_biforme_DSM_3989',
                  'Clostridium_asparagiforme_DSM_15981',
                  'Bifidobacterium_angulatum_DSM_20098_=_JCM_7096',
                  'Bifidobacterium_breve_DSM_20213_=_JCM_1192',
                  'Bifidobacterium_animalis_subsp._lactis_AD011',
                  'Lactobacillus_buchneri_ATCC_11577',
                  'Oxalobacter_formigenes_HOxBLS',
                  'Bifidobacterium_gallicum_DSM_20093',
                  'Bifidobacterium_catenulatum_DSM_16992_=_JCM_1194',
                  'Helicobacter_pullorum_MIT_98_5489',
                  'Clostridium_hylemonae_DSM_15053',
                  'Helicobacter_canadensis_MIT_98_5491',
                  'Fusobacterium_varium_ATCC_27725',
                  'Fusobacterium_ulcerans_ATCC_49185',
                  'Fusobacterium_gonidiaformans_ATCC_25563',
                  'Roseburia_inulinivorans_DSM_16841',
                  'Clostridium_methylpentosum_DSM_5476',
                  'Escherichia_coli_SE11',
                  'Bacteroides_eggerthii_DSM_20697',
                  'Faecalibacterium_prausnitzii_A2_165',
                  'Lactobacillus_antri_DSM_16041',
                  'Bacteroides_finegoldii_DSM_17565',
                  'Bifidobacterium_pseudocatenulatum_DSM_20438_=_JCM_1200',
                  'Lactobacillus_helveticus_DPC_4571',
                  'Anaerostipes_caccae_DSM_14662',
                  'Catenibacterium_mitsuokai_DSM_15897',
                  'Enterococcus_faecium_TX1330',
                  'Helicobacter_winghamensis_ATCC_BAA_430',
                  'Providencia_alcalifaciens_DSM_30120',
                  'Bacteroides_vulgatus_ATCC_8482',
                  'Parabacteroides_distasonis_ATCC_8503',
                  'Clostridium_hathewayi_DSM_13479',
                  'Bacteroides_dorei_DSM_17855',
                  '[Bacteroides]_pectinophilus_ATCC_43243',
                  'Bifidobacterium_dentium_ATCC_27678',
                  'Anaerobaculum_hydrogeniformans_ATCC_BAA_1850',
                  'Ruminococcus_champanellensis_18P13',
                  'Clostridium_scindens_ATCC_35704',
                  'Eubacterium_hallii_DSM_3353',
                  'Holdemania_filiformis_DSM_12042',
                  'Dorea_longicatena_DSM_13814',
                  'Eubacterium_ventriosum_ATCC_27560',
                  'Roseburia_intestinalis_L1_82',
                  'Dorea_formicigenerans_ATCC_27755',
                  'Actinomyces_odontolyticus_ATCC_17982',
                  'Pseudoflavonifractor_capillosus_ATCC_29799',
                  'Desulfovibrio_piger_ATCC_29098',
                  'Parvimonas_micra_ATCC_33270',
                  'Bacteroides_plebeius_DSM_17135',
                  'Lactobacillus_ultunensis_DSM_16047',
                  'Listeria_grayi_DSM_20601',
                  'Lactobacillus_rhamnosus_LMS2_1',
                  'Leuconostoc_mesenteroides_subsp._cremoris_ATCC_19254',
                  'Bacteroides_xylanisolvens_XB1A',
                  'Fusobacterium_mortiferum_ATCC_9817',
                  'Citrobacter_youngae_ATCC_29220',
                  'Providencia_rettgeri_DSM_1131',
                  'Bacteroides_uniformis_ATCC_8492',
                  'Lactobacillus_hilgardii_ATCC_8290',
                  'Subdoligranulum_variabile_DSM_15176',
                  'Ruminococcus_gnavus_ATCC_29149',
                  'Bifidobacterium_bifidum_NCIMB_41171',
                  'Coprococcus_eutactus_ATCC_27759',
                  'Parabacteroides_merdae_ATCC_43184',
                  'Bacteroides_ovatus_ATCC_8483',
                  'Weissella_paramesenteroides_ATCC_33313']

metagenome_orgs = ["metagenome"]
# this list was corrected from old_reference_orgs by matching several
# species names to the folders contained in
# erilllab.biosci.umbc.edu:metagenomics/genomes and matching by
# minimum Levenshtein distance.  All matches were visually inspected
# afterwards for sanity checking.

reference_orgs = ['Lactobacillus_johnsonii_NCC_533',
                  'Bacteroides_fragilis_YCH46',
                  'Lactobacillus_acidophilus_NCFM',
                  'Lactobacillus_salivarius_UCC118',
                  'Lactobacillus_gasseri_ATCC_33323',
                  'Lactobacillus_casei_ATCC_334',
                  'Lactobacillus_reuteri_DSM_20016',
                  'Methanobrevibacter_smithii_ATCC_35061',
                  'Bacteroides_caccae_ATCC_43185',
                  'Collinsella_aerofaciens_ATCC_25986',
                  'Lactobacillus_brevis_ATCC_367',
                  'Bifidobacterium_adolescentis_ATCC_15703',
                  'Ruminococcus_torques_ATCC_27756',
                  'Bacteroides_stercoris_ATCC_43183',
                  'Ruminococcus_obeum_ATCC_29174',
                  'Bryantella_formatexigens_DSM_14469',
                  'Providencia_rustigianii_DSM_4541',
                  'Mitsuokella_multacida_DSM_20544',
                  'Clostridium_nexile_DSM_1787',
                  'Clostridium_hiranonis_DSM_13275',
                  'Butyrivibrio_crossotus_DSM_2876',
                  'Prevotella_copri_DSM_18205',
                  'Bacteroides_cellulosilyticus_DSM_14838',
                  'Alistipes_putredinis_DSM_17216',
                  'Enterobacter_cancerogenus_ATCC_35316',
                  'Bacteroides_coprophilus_DSM_18228',
                  'Fusobacterium_7_1',
                  'Collinsella_stercoris_DSM_13279',
                  'Blautia_hansenii_DSM_20583',
                  'Parabacteroides_johnsonii_DSM_18315',
                  'Clostridium_bolteae_ATCC_BAA_613',
                  'Helicobacter_bilis_ATCC_43879',
                  'Bifidobacterium_longum_infantis_ATCC_55813',
                  'Clostridium_sporogenes_ATCC_15579',
                  'Bacteroides_intestinalis_DSM_17393',
                  'Ruminococcus_lactaris_ATCC_29176',
                  'Providencia_stuartii_ATCC_25827',
                  'Eubacterium_dolichum_DSM_3991',
                  'Clostridium_spiroforme_DSM_1552',
                  'Clostridium_leptum_DSM_753',
                  'Enterococcus_faecalis_TX0104',
                  'Eubacterium_siraeum_DSM_15702',
                  'Helicobacter_cinaedi_CCUG_18818',
                  'Lactobacillus_ruminis_ATCC_25644',
                  'Blautia_hydrogenotrophica_DSM_10507',
                  'Gordonibacter_pamelaeae_7_10_1_b',
                  'Lactobacillus_fermentum_ATCC_14931',
                  'Collinsella_intestinalis_DSM_13280',
                  'Anaerofustis_stercorihominis_DSM_17244',
                  'Clostridium_bartlettii_DSM_16795',
                  'Anaerotruncus_colihominis_DSM_17241',
                  'Clostridium_ramosum_DSM_1402',
                  'Proteus_penneri_ATCC_35198',
                  'Anaerococcus_hydrogenalis_DSM_7454',
                  'Bacteroides_coprocola_DSM_17136',
                  'Coprococcus_comes_ATCC_27758',
                  'Eubacterium_biforme_DSM_3989',
                  'Clostridium_asparagiforme_DSM_15981',
                  'Bifidobacterium_angulatum_DSM_20098',
                  'Bifidobacterium_breve_DSM_20213',
                  'Bifidobacterium_animalis_lactis_AD011',
                  'Lactobacillus_buchneri_ATCC_11577',
                  'Oxalobacter_formigenes_HOxBLS',
                  'Bifidobacterium_gallicum_DSM_20093',
                  'Bifidobacterium_catenulatum_DSM_16992',
                  'Helicobacter_pullorum_MIT_98_5489',
                  'Clostridium_hylemonae_DSM_15053',
                  'Helicobacter_canadensis_MIT_98_5491',
                  'Fusobacterium_varium_ATCC_27725',
                  'Fusobacterium_ulcerans_ATCC_49185',
                  'Fusobacterium_gonidiaformans_ATCC_25563',
                  'Roseburia_inulinivorans_DSM_16841',
                  'Clostridium_methylpentosum_DSM_5476',
                  'Escherichia_coli_SE11',
                  'Bacteroides_eggerthii_DSM_20697',
                  'Faecalibacterium_prausnitzii_A2_165',
                  'Lactobacillus_antri_DSM_16041',
                  'Bacteroides_finegoldii_DSM_17565',
                  'Bifidobacterium_pseudocatenulatum_DSM_20438',
                  'Lactobacillus_helveticus_DPC_4571',
                  'Anaerostipes_caccae_DSM_14662',
                  'Catenibacterium_mitsuokai_DSM_15897',
                  'Enterococcus_faecium_TX1330',
                  'Helicobacter_winghamensis_ATCC_BAA_430',
                  'Providencia_alcalifaciens_DSM_30120',
                  'Bacteroides_vulgatus_ATCC_8482',
                  'Parabacteroides_distasonis_ATCC_8503',
                  'Clostridium_hathewayi_DSM_13479',
                  'Bacteroides_dorei_DSM_17855',
                  'Bacteroides_pectinophilus_ATCC_43243',
                  'Bifidobacterium_dentium_ATCC_27678',
                  'Anaerobaculum_hydrogeniformans_ATCC_BAA_1850',
                  'Ruminococcus_18P13',
                  'Clostridium_scindens_ATCC_35704',
                  'Eubacterium_hallii_DSM_3353',
                  'Holdemania_filiformis_DSM_12042',
                  'Dorea_longicatena_DSM_13814',
                  'Eubacterium_ventriosum_ATCC_27560',
                  'Roseburia_intestinalis_L1_82',
                  'Dorea_formicigenerans_ATCC_27755',
                  'Actinomyces_odontolyticus_ATCC_17982',
                  'Bacteroides_capillosus_ATCC_29799',
                  'Desulfovibrio_piger_ATCC_29098',
                  'Parvimonas_micra_ATCC_33270',
                  'Bacteroides_plebeius_DSM_17135',
                  'Lactobacillus_ultunensis_DSM_16047',
                  'Listeria_grayi_DSM_20601',
                  'Lactobacillus_rhamnosus_LMS2_1',
                  'Leuconostoc_mesenteroides_cremoris_ATCC_19254',
                  'Bacteroides_xylanisolvens_XB1A',
                  'Fusobacterium_mortiferum_ATCC_9817',
                  'Citrobacter_youngae_ATCC_29220',
                  'Providencia_rettgeri_DSM_1131',
                  'Bacteroides_uniformis_ATCC_8492',
                  'Lactobacillus_hilgardii_ATCC_8290',
                  'Subdoligranulum_variabile_DSM_15176',
                  'Ruminococcus_gnavus_ATCC_29149',
                  'Bifidobacterium_bifidum_NCIMB_41171',
                  'Coprococcus_eutactus_ATCC_27759',
                  'Parabacteroides_merdae_ATCC_43184',
                  'Bacteroides_ovatus_ATCC_8483',
                  'Weissella_paramesenteroides_ATCC_33313']

test_reference_orgs = reference_orgs[:1]

joe_reference_orgs = ["Acidaminococcus_D21",
                      "Actinomyces_odontolyticus_ATCC_17982",
                      "Alistipes_putredinis_DSM_17216",
                      "Anaerobaculum_hydrogeniformans_ATCC_BAA_1850",
                      "Anaerococcus_hydrogenalis_DSM_7454",
                      "Anaerofustis_stercorihominis_DSM_17244",
                      "Anaerostipes_caccae_DSM_14662",
                      "Anaerotruncus_colihominis_DSM_17241",
                      "Bacteroides_1_1_6",
                      "Bacteroides_2_1_7",
                      "Bacteroides_2_2_4",
                      "Bacteroides_3_2_5",
                      "Bacteroides_4_3_47FAA",
                      "Bacteroides_9_1_42FAA",
                      "Bacteroides_caccae_ATCC_43185",
                      "Bacteroides_capillosus_ATCC_29799",
                      "Bacteroides_cellulosilyticus_DSM_14838",
                      "Bacteroides_coprocola_DSM_17136",
                      "Bacteroides_coprophilus_DSM_18228",
                      "Bacteroides_D1",
                      "Bacteroides_D2",
                      "Bacteroides_dorei_DSM_17855",
                      "Bacteroides_eggerthii_DSM_20697",
                      "Bacteroides_finegoldii_DSM_17565",
                      "Bacteroides_fragilis_3_1_12",
                      "Bacteroides_fragilis_YCH46",
                      "Bacteroides_intestinalis_DSM_17393",
                      "Bacteroides_ovatus_ATCC_8483",
                      "Bacteroides_pectinophilus_ATCC_43243",
                      "Bacteroides_plebeius_DSM_17135",
                      "Bacteroides_stercoris_ATCC_43183",
                      "Bacteroides_uniformis_ATCC_8492",
                      "Bacteroides_vulgatus_ATCC_8482",
                      "Bacteroides_xylanisolvens_XB1A",
                      "Bifidobacterium_adolescentis_ATCC_15703",
                      "Bifidobacterium_adolescentis_L2_32",
                      "Bifidobacterium_angulatum_DSM_20098",
                      "Bifidobacterium_animalis_lactis_AD011",
                      "Bifidobacterium_bifidum_NCIMB_41171",
                      "Bifidobacterium_breve_DSM_20213",
                      "Bifidobacterium_catenulatum_DSM_16992",
                      "Bifidobacterium_dentium_ATCC_27678",
                      "Bifidobacterium_gallicum_DSM_20093",
                      "Bifidobacterium_longum_DJO10A",
                      "Bifidobacterium_longum_infantis_ATCC_15697",
                      "Bifidobacterium_longum_infantis_ATCC_55813",
                      "Bifidobacterium_longum_infantis_CCUG_52486",
                      "Bifidobacterium_pseudocatenulatum_DSM_20438",
                      "Blautia_hansenii_DSM_20583",
                      "Blautia_hydrogenotrophica_DSM_10507",
                      "Bryantella_formatexigens_DSM_14469",
                      "Butyrivibrio_crossotus_DSM_2876",
                      "Catenibacterium_mitsuokai_DSM_15897",
                      "Citrobacter_30_2",
                      "Citrobacter_youngae_ATCC_29220",
                      "Clostridiales_bacterium_1_7_47FAA",
                      "Clostridium_7_2_43FAA",
                      "Clostridium_asparagiforme_DSM_15981",
                      "Clostridium_bartlettii_DSM_16795",
                      "Clostridium_bolteae_ATCC_BAA_613",
                      "Clostridium_hathewayi_DSM_13479",
                      "Clostridium_hiranonis_DSM_13275",
                      "Clostridium_hylemonae_DSM_15053",
                      "Clostridium_L2_50",
                      "Clostridium_leptum_DSM_753",
                      "Clostridium_M62_1",
                      "Clostridium_methylpentosum_DSM_5476",
                      "Clostridium_nexile_DSM_1787",
                      "Clostridium_ramosum_DSM_1402",
                      "Clostridium_scindens_ATCC_35704",
                      "Clostridium_spiroforme_DSM_1552",
                      "Clostridium_sporogenes_ATCC_15579",
                      "Clostridium_SS2_1",
                      "Collinsella_aerofaciens_ATCC_25986",
                      "Collinsella_intestinalis_DSM_13280",
                      "Collinsella_stercoris_DSM_13279",
                      "Coprococcus_comes_ATCC_27758",
                      "Coprococcus_eutactus_ATCC_27759",
                      "Desulfovibrio_piger_ATCC_29098",
                      "Dorea_formicigenerans_ATCC_27755",
                      "Dorea_longicatena_DSM_13814",
                      "Enterobacter_cancerogenus_ATCC_35316",
                      "Enterococcus_7L76",
                      "Enterococcus_faecalis_TX0104",
                      "Enterococcus_faecalis_TX1322",
                      "Enterococcus_faecium_TX1330",
                      "Escherichia_1_1_43",
                      "Escherichia_3_2_53FAA",
                      "Escherichia_4_1_40B",
                      "Escherichia_coli_SE11",
                      "Eubacterium_biforme_DSM_3989",
                      "Eubacterium_dolichum_DSM_3991",
                      "Eubacterium_hallii_DSM_3353",
                      "Eubacterium_siraeum_DSM_15702",
                      "Eubacterium_ventriosum_ATCC_27560",
                      "Faecalibacterium_prausnitzii_A2_165",
                      "Faecalibacterium_prausnitzii_M21_2",
                      "Fusobacterium_2_1_31",
                      "Fusobacterium_4_1_13",
                      "Fusobacterium_7_1",
                      "Fusobacterium_D11",
                      "Fusobacterium_D12",
                      "Fusobacterium_gonidiaformans_ATCC_25563",
                      "Fusobacterium_mortiferum_ATCC_9817",
                      "Fusobacterium_ulcerans_ATCC_49185",
                      "Fusobacterium_varium_ATCC_27725",
                      "Gordonibacter_pamelaeae_7_10_1_b",
                      "Helicobacter_bilis_ATCC_43879",
                      "Helicobacter_canadensis_MIT_98_5491",
                      "Helicobacter_cinaedi_CCUG_18818",
                      "Helicobacter_pullorum_MIT_98_5489",
                      "Helicobacter_winghamensis_ATCC_BAA_430",
                      "Holdemania_filiformis_DSM_12042",
                      "Lactobacillus_acidophilus_ATCC_4796",
                      "Lactobacillus_acidophilus_NCFM",
                      "Lactobacillus_antri_DSM_16041",
                      "Lactobacillus_brevis_ATCC_367",
                      "Lactobacillus_brevis_gravesensis_ATCC_27305",
                      "Lactobacillus_buchneri_ATCC_11577",
                      "Lactobacillus_casei_ATCC_334",
                      "Lactobacillus_fermentum_ATCC_14931",
                      "Lactobacillus_fermentum_IFO_3956",
                      "Lactobacillus_gasseri_ATCC_33323",
                      "Lactobacillus_helveticus_DPC_4571",
                      "Lactobacillus_helveticus_DSM_20075",
                      "Lactobacillus_hilgardii_ATCC_8290",
                      "Lactobacillus_johnsonii_NCC_533",
                      "Lactobacillus_reuteri_CF48_3A",
                      "Lactobacillus_reuteri_DSM_20016",
                      "Lactobacillus_reuteri_MM2_3",
                      "Lactobacillus_reuteri_MM4_1A",
                      "Lactobacillus_reuteri_SD2112",
                      "Lactobacillus_rhamnosus_LMS2_1",
                      "Lactobacillus_ruminis_ATCC_25644",
                      "Lactobacillus_salivarius_ATCC_11741",
                      "Lactobacillus_salivarius_UCC118",
                      "Lactobacillus_ultunensis_DSM_16047",
                      "Leuconostoc_mesenteroides_cremoris_ATCC_19254",
                      "Listeria_grayi_DSM_20601",
                      "Methanobrevibacter_smithii_ATCC_35061",
                      "Methanobrevibacter_smithii_DSM_2374",
                      "Methanobrevibacter_smithii_DSM_2375",
                      "Mitsuokella_multacida_DSM_20544",
                      "Mollicutes_bacterium_D7",
                      "Oxalobacter_formigenes_HOxBLS",
                      "Oxalobacter_formigenes_OXCC13",
                      "Parabacteroides_distasonis_ATCC_8503",
                      "Parabacteroides_johnsonii_DSM_18315",
                      "Parabacteroides_merdae_ATCC_43184",
                      "Parvimonas_micra_ATCC_33270",
                      "Prevotella_copri_DSM_18205",
                      "Proteus_penneri_ATCC_35198",
                      "Providencia_alcalifaciens_DSM_30120",
                      "Providencia_rettgeri_DSM_1131",
                      "Providencia_rustigianii_DSM_4541",
                      "Providencia_stuartii_ATCC_25827",
                      "Roseburia_intestinalis_L1_82",
                      "Roseburia_inulinivorans_DSM_16841",
                      "Ruminococcus_18P13",
                      "Ruminococcus_5_1_39BFAA",
                      "Ruminococcus_gnavus_ATCC_29149",
                      "Ruminococcus_lactaris_ATCC_29176",
                      "Ruminococcus_obeum_ATCC_29174",
                      "Ruminococcus_torques_ATCC_27756",
                      "Subdoligranulum_variabile_DSM_15176",
                      "Weissella_paramesenteroides_ATCC_33313"]

do_overs = ['Providencia_stuartii_ATCC_25827',
            'Clostridium_spiroforme_DSM_1552',
            'Clostridium_leptum_DSM_753',
            'Enterococcus_faecalis_TX0104',
            'Lactobacillus_ruminis_ATCC_25644',
            'Bacteroides_coprocola_DSM_17136',
            'Coprococcus_comes_ATCC_27758',
            'Eubacterium_biforme_DSM_3989',
            'Clostridium_asparagiforme_DSM_15981',
            'Bifidobacterium_angulatum_DSM_20098',
            'Bifidobacterium_breve_DSM_20213',
            'Bifidobacterium_animalis_lactis_AD011',
            'Lactobacillus_buchneri_ATCC_11577',
            'Oxalobacter_formigenes_HOxBLS',
            'Bifidobacterium_gallicum_DSM_20093',
            'Bifidobacterium_catenulatum_DSM_16992',
            'Helicobacter_pullorum_MIT_98_5489',
            'Clostridium_hylemonae_DSM_15053',
            'Helicobacter_canadensis_MIT_98_5491',
            'Fusobacterium_varium_ATCC_27725',
            'Fusobacterium_ulcerans_ATCC_49185',
            'Fusobacterium_gonidiaformans_ATCC_25563',
            'Roseburia_inulinivorans_DSM_16841',
            'Clostridium_methylpentosum_DSM_5476',
            'Escherichia_coli_SE11',
            'Bacteroides_eggerthii_DSM_20697',
            'Faecalibacterium_prausnitzii_A2_165',
            'Lactobacillus_antri_DSM_16041',
            'Bifidobacterium_pseudocatenulatum_DSM_20438',
            'Lactobacillus_helveticus_DPC_4571',
            'Catenibacterium_mitsuokai_DSM_15897',
            'Helicobacter_winghamensis_ATCC_BAA_430']

do_overs2 = ['Ruminococcus_lactaris_ATCC_29176',
             'Providencia_stuartii_ATCC_25827',
             'Clostridium_spiroforme_DSM_1552',
             'Clostridium_leptum_DSM_753',
             'Enterococcus_faecalis_TX0104',
             'Lactobacillus_ruminis_ATCC_25644']

do_overs3 = ['Clostridium_spiroforme_DSM_1552',
             'Clostridium_leptum_DSM_753',
             'Enterococcus_faecalis_TX0104',
             'Lactobacillus_ruminis_ATCC_25644']

orgs = ["Acinetobacter_ADP1",
        "Pseudomonas_fluorescens", 
        "Acinetobacter_baumannii", 
        "Pseudomonas_fulva", 
        "Azotobacter_vinelandii", 
        "Pseudomonas_mendocina", 
        "Cellvibrio__gilvus", 
        "Pseudomonas_putida", 
        "Cellvibrio_japonicus", 
        "Pseudomonas_stutzeri", 
        "Pseudomonas_syringae", 
        "Moraxella_catarrhalis", 
        "Psychrobacter_arcticus_273", 
        "Pseudomonas_aeruginosa",  
        "Psychrobacter_cryohalolentis", 
        "Pseudomonas_brassicacearum", 
        "Psychrobacter_PRwf", 
        "Pseudomonas_entomophila"]

gammas = ["Haemophilus_influenzae", 
          "Escherichia_coli", 
          "Salmonella_typhimurium", 
          "Shewanella_oneidensis", 
          "Vibrio_cholerae"
          ]

firmicutes = ["Bacillus_subtilis", 
              "Lactobacillus_plantarum", 
              "Lactococcus_lactis", 
              "Bacillus_halodurans", 
              "Enterococcus_faecalis", 
              ]
#
actinos = ["Arthrobacter", 
           "Mycobacterium_smegmatis", 
           "Streptomyces_coelicolor", 
           "Bifidobacterium_breve", 
           "Corynebacterium_diphtheriae"]
misc = ["Helicobacter_pylori_HPAG1",
        ]
enteros = ["Enterococcus_faecalis",
           "Bifidobacterium_breve",
           "Bacteroides_thetaiotaomicron",
           "Fusobacterium_nucleatum",
           "Lactobacillus_gasseri",
           "Proteus_mirabilis",
           "Escherichia_coli",
           "Eubacterium_rectale"]

acinetos = ["Acinetobacter_baumannii",
               "Acinetobacter_ADP1",
               "Acinetobacter_calcoaceticus",
               "Acinetobacter_oleivorans"]

pseudos = [org for org in orgs if "Pseudo" in org]
psychros = [org for org in orgs if "Psychro" in org]
all_orgs = list(set(orgs + gammas + firmicutes + actinos + enteros))
new_orgs = gammas + firmicutes
pvp_orgs = pseudos + psychros
last_orgs = pvp_orgs + new_orgs + actinos
ecoli = "Escherichia_coli"
group_names = ["pseudos","psychros","pvp_orgs","gammas",
               "firmicutes","enteros","actinos","last_orgs"]

def org_group(org):
    # lookup = {"pseudos":pseudos,
    #           "psychros":psychros,
    #           "gammas":gammas,
    #           "firmicutes":firmicutes,
    #           "actinos":actinos,
    #           "enteros":enteros,
    #           "all_orgs":all_orgs
    #           }
    for group in ["pseudos",
              "psychros",
              "gammas",
              "firmicutes",
              "actinos",
              "enteros",
              "all_orgs"]:
        if org in lookup[group]:
            return group
    assert False, "couldn't find %s in lookup table" % org
    
del(org) # namespace leak
